# Generated by Django 5.0.7 on 2024-07-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
