# Generated by Django 5.0.7 on 2024-07-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_for_who_course_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='for_who',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
