# Generated by Django 5.0.7 on 2024-07-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_for_who_alter_course_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
